package com.cooklist.bean.entity;
// Generated 6 sept 2024 0:18:04 by Hibernate Tools 5.2.13.Final

import java.math.BigDecimal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * MealDetail generated by hbm2java
 */
@Entity
@Table(name = "meal_detail", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "meal_id",
		"measured_ingredient_id" }))
public class MealDetailEntity implements java.io.Serializable {

	private static final long serialVersionUID = -7968448591569186872L;
	private Integer id;
	private MealEntity meal;
	private MeasuredIngredientEntity measuredIngredient;
	private BigDecimal quantity;

	public MealDetailEntity() {
	}

	public MealDetailEntity(Integer id, MealEntity meal, MeasuredIngredientEntity measuredIngredient, BigDecimal quantity) {
		this.id = id;
		this.meal = meal;
		this.measuredIngredient = measuredIngredient;
		this.quantity = quantity;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "meal_id", nullable = false)
	public MealEntity getMeal() {
		return this.meal;
	}

	public void setMeal(MealEntity meal) {
		this.meal = meal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "measured_ingredient_id", nullable = false)
	public MeasuredIngredientEntity getMeasuredIngredient() {
		return this.measuredIngredient;
	}

	public void setMeasuredIngredient(MeasuredIngredientEntity measuredIngredient) {
		this.measuredIngredient = measuredIngredient;
	}

	@Column(name = "quantity", nullable = false, precision = 10, scale = 3)
	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

}
