package com.cooklist.bean.entity;
// Generated 6 sept 2024 0:18:04 by Hibernate Tools 5.2.13.Final

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * MealProgramming generated by hbm2java
 */
@Entity
@Table(name = "meal_programming", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"app_user_id", "programming" }))
public class MealProgrammingEntity implements java.io.Serializable {

	private static final long serialVersionUID = -6482200501639886082L;
	private Integer id;
	private MealEntity meal;
	private AppUserEntity appUser;
	private Date programming;

	public MealProgrammingEntity() {
	}

	public MealProgrammingEntity(Integer id, MealEntity meal, AppUserEntity appUser, Date programming) {
		this.id = id;
		this.meal = meal;
		this.appUser = appUser;
		this.programming = programming;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "meal_id")
	public MealEntity getMeal() {
		return this.meal;
	}

	public void setMeal(MealEntity meal) {
		this.meal = meal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "app_user_id", nullable = false)
	public AppUserEntity getAppUser() {
		return this.appUser;
	}

	public void setAppUser(AppUserEntity appUser) {
		this.appUser = appUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "programming", nullable = false, length = 13)
	public Date getProgramming() {
		return this.programming;
	}

	public void setProgramming(Date programming) {
		this.programming = programming;
	}

}
