package com.cooklist.bean.entity;
// Generated 6 sept 2024 0:18:04 by Hibernate Tools 5.2.13.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * MeasuredIngredient generated by hbm2java
 */
@Entity
@Table(name = "measured_ingredient", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ingredient_id", "measurement_unit_id" }))
public class MeasuredIngredientEntity implements java.io.Serializable {

	private static final long serialVersionUID = 2698336003556163081L;
	private Integer id;
	private IngredientEntity ingredient;
	private MeasurementUnitEntity measurementUnit;
	private Set<MealDetailEntity> mealDetails = new HashSet<MealDetailEntity>(0);

	public MeasuredIngredientEntity() {
	}

	public MeasuredIngredientEntity(Integer id, IngredientEntity ingredient, MeasurementUnitEntity measurementUnit) {
		this.id = id;
		this.ingredient = ingredient;
		this.measurementUnit = measurementUnit;
	}

	public MeasuredIngredientEntity(Integer id, IngredientEntity ingredient, MeasurementUnitEntity measurementUnit,
			Set<MealDetailEntity> mealDetails) {
		this.id = id;
		this.ingredient = ingredient;
		this.measurementUnit = measurementUnit;
		this.mealDetails = mealDetails;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ingredient_id", nullable = false)
	public IngredientEntity getIngredient() {
		return this.ingredient;
	}

	public void setIngredient(IngredientEntity ingredient) {
		this.ingredient = ingredient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "measurement_unit_id", nullable = false)
	public MeasurementUnitEntity getMeasurementUnit() {
		return this.measurementUnit;
	}

	public void setMeasurementUnit(MeasurementUnitEntity measurementUnit) {
		this.measurementUnit = measurementUnit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "measuredIngredient", cascade = CascadeType.REMOVE, orphanRemoval = true)
	public Set<MealDetailEntity> getMealDetails() {
		return this.mealDetails;
	}

	public void setMealDetails(Set<MealDetailEntity> mealDetails) {
		this.mealDetails = mealDetails;
	}

}
