package com.cooklist.bean.entity;
// Generated 6 sept 2024 0:18:04 by Hibernate Tools 5.2.13.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * MeasurementUnit generated by hbm2java
 */
@Entity
@Table(name = "measurement_unit", schema = "public", uniqueConstraints = { @UniqueConstraint(columnNames = "name"),
		@UniqueConstraint(columnNames = "symbol") })
public class MeasurementUnitEntity implements java.io.Serializable {

	private static final long serialVersionUID = 6975256292822863987L;
	private Integer id;
	private String name;
	private String symbol;
	private boolean isMeasurable;
	private Set<MeasuredIngredientEntity> measuredIngredients = new HashSet<MeasuredIngredientEntity>(0);

	public MeasurementUnitEntity() {
	}

	public MeasurementUnitEntity(Integer id, String name, String symbol, boolean isMeasurable) {
		this.id = id;
		this.name = name;
		this.symbol = symbol;
		this.isMeasurable = isMeasurable;
	}

	public MeasurementUnitEntity(Integer id, String name, String symbol, boolean isMeasurable,
			Set<MeasuredIngredientEntity> measuredIngredients) {
		this.id = id;
		this.name = name;
		this.symbol = symbol;
		this.isMeasurable = isMeasurable;
		this.measuredIngredients = measuredIngredients;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "symbol", unique = true, nullable = false, length = 10)
	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	@Column(name = "is_measurable", nullable = false)
	public boolean isIsMeasurable() {
		return this.isMeasurable;
	}

	public void setIsMeasurable(boolean isMeasurable) {
		this.isMeasurable = isMeasurable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "measurementUnit")
	public Set<MeasuredIngredientEntity> getMeasuredIngredients() {
		return this.measuredIngredients;
	}

	public void setMeasuredIngredients(Set<MeasuredIngredientEntity> measuredIngredients) {
		this.measuredIngredients = measuredIngredients;
	}

}
